# Generated by Django 4.2.16 on 2024-11-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('pdf', 'PDF File')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_pdfs/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
